[build]
  command = "npm run build"
  publish = ".next"

[[edge_functions]]
  path = "/api/*"
  function = "next"

[functions]
  external_node_modules = ["openai", "nodemailer"]
  node_bundler = "esbuild"
